# Generated by Django 4.2.4 on 2023-10-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=255)),
                ('adm_no', models.IntegerField()),
                ('Form', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('Stream', models.CharField(choices=[('G', 'G'), ('B', 'B'), ('H', 'H'), ('S', 'S'), ('F', 'F'), ('A', 'A')], max_length=1)),
            ],
        ),
    ]
