# Generated by Django 4.2.4 on 2023-10-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetail',
            old_name='Full_name',
            new_name='First_name',
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='Last_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='Middle_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
